	lab4 u0 (
		.clk_65_clk                         (<connected-to-clk_65_clk>),                         //               clk_65.clk
		.clocked_video_export_vid_clk       (<connected-to-clocked_video_export_vid_clk>),       // clocked_video_export.vid_clk
		.clocked_video_export_vid_data      (<connected-to-clocked_video_export_vid_data>),      //                     .vid_data
		.clocked_video_export_underflow     (<connected-to-clocked_video_export_underflow>),     //                     .underflow
		.clocked_video_export_vid_datavalid (<connected-to-clocked_video_export_vid_datavalid>), //                     .vid_datavalid
		.clocked_video_export_vid_v_sync    (<connected-to-clocked_video_export_vid_v_sync>),    //                     .vid_v_sync
		.clocked_video_export_vid_h_sync    (<connected-to-clocked_video_export_vid_h_sync>),    //                     .vid_h_sync
		.clocked_video_export_vid_f         (<connected-to-clocked_video_export_vid_f>),         //                     .vid_f
		.clocked_video_export_vid_h         (<connected-to-clocked_video_export_vid_h>),         //                     .vid_h
		.clocked_video_export_vid_v         (<connected-to-clocked_video_export_vid_v>),         //                     .vid_v
		.cont_from_hps_export               (<connected-to-cont_from_hps_export>),               //        cont_from_hps.export
		.done_to_hps_export                 (<connected-to-done_to_hps_export>),                 //          done_to_hps.export
		.hps_0_h2f_reset_reset_n            (<connected-to-hps_0_h2f_reset_reset_n>),            //      hps_0_h2f_reset.reset_n
		.hps_io_hps_io_sdio_inst_CMD        (<connected-to-hps_io_hps_io_sdio_inst_CMD>),        //               hps_io.hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0         (<connected-to-hps_io_hps_io_sdio_inst_D0>),         //                     .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1         (<connected-to-hps_io_hps_io_sdio_inst_D1>),         //                     .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK        (<connected-to-hps_io_hps_io_sdio_inst_CLK>),        //                     .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2         (<connected-to-hps_io_hps_io_sdio_inst_D2>),         //                     .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3         (<connected-to-hps_io_hps_io_sdio_inst_D3>),         //                     .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0         (<connected-to-hps_io_hps_io_usb1_inst_D0>),         //                     .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1         (<connected-to-hps_io_hps_io_usb1_inst_D1>),         //                     .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2         (<connected-to-hps_io_hps_io_usb1_inst_D2>),         //                     .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3         (<connected-to-hps_io_hps_io_usb1_inst_D3>),         //                     .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4         (<connected-to-hps_io_hps_io_usb1_inst_D4>),         //                     .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5         (<connected-to-hps_io_hps_io_usb1_inst_D5>),         //                     .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6         (<connected-to-hps_io_hps_io_usb1_inst_D6>),         //                     .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7         (<connected-to-hps_io_hps_io_usb1_inst_D7>),         //                     .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK        (<connected-to-hps_io_hps_io_usb1_inst_CLK>),        //                     .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP        (<connected-to-hps_io_hps_io_usb1_inst_STP>),        //                     .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR        (<connected-to-hps_io_hps_io_usb1_inst_DIR>),        //                     .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT        (<connected-to-hps_io_hps_io_usb1_inst_NXT>),        //                     .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX        (<connected-to-hps_io_hps_io_uart0_inst_RX>),        //                     .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX        (<connected-to-hps_io_hps_io_uart0_inst_TX>),        //                     .hps_io_uart0_inst_TX
		.led_export_export                  (<connected-to-led_export_export>),                  //           led_export.export
		.memory_mem_a                       (<connected-to-memory_mem_a>),                       //               memory.mem_a
		.memory_mem_ba                      (<connected-to-memory_mem_ba>),                      //                     .mem_ba
		.memory_mem_ck                      (<connected-to-memory_mem_ck>),                      //                     .mem_ck
		.memory_mem_ck_n                    (<connected-to-memory_mem_ck_n>),                    //                     .mem_ck_n
		.memory_mem_cke                     (<connected-to-memory_mem_cke>),                     //                     .mem_cke
		.memory_mem_cs_n                    (<connected-to-memory_mem_cs_n>),                    //                     .mem_cs_n
		.memory_mem_ras_n                   (<connected-to-memory_mem_ras_n>),                   //                     .mem_ras_n
		.memory_mem_cas_n                   (<connected-to-memory_mem_cas_n>),                   //                     .mem_cas_n
		.memory_mem_we_n                    (<connected-to-memory_mem_we_n>),                    //                     .mem_we_n
		.memory_mem_reset_n                 (<connected-to-memory_mem_reset_n>),                 //                     .mem_reset_n
		.memory_mem_dq                      (<connected-to-memory_mem_dq>),                      //                     .mem_dq
		.memory_mem_dqs                     (<connected-to-memory_mem_dqs>),                     //                     .mem_dqs
		.memory_mem_dqs_n                   (<connected-to-memory_mem_dqs_n>),                   //                     .mem_dqs_n
		.memory_mem_odt                     (<connected-to-memory_mem_odt>),                     //                     .mem_odt
		.memory_mem_dm                      (<connected-to-memory_mem_dm>),                      //                     .mem_dm
		.memory_oct_rzqin                   (<connected-to-memory_oct_rzqin>),                   //                     .oct_rzqin
		.ready_from_hps_export              (<connected-to-ready_from_hps_export>),              //       ready_from_hps.export
		.sdram_wire_addr                    (<connected-to-sdram_wire_addr>),                    //           sdram_wire.addr
		.sdram_wire_ba                      (<connected-to-sdram_wire_ba>),                      //                     .ba
		.sdram_wire_cas_n                   (<connected-to-sdram_wire_cas_n>),                   //                     .cas_n
		.sdram_wire_cke                     (<connected-to-sdram_wire_cke>),                     //                     .cke
		.sdram_wire_cs_n                    (<connected-to-sdram_wire_cs_n>),                    //                     .cs_n
		.sdram_wire_dq                      (<connected-to-sdram_wire_dq>),                      //                     .dq
		.sdram_wire_dqm                     (<connected-to-sdram_wire_dqm>),                     //                     .dqm
		.sdram_wire_ras_n                   (<connected-to-sdram_wire_ras_n>),                   //                     .ras_n
		.sdram_wire_we_n                    (<connected-to-sdram_wire_we_n>),                    //                     .we_n
		.sobel_0_debug_cont                 (<connected-to-sobel_0_debug_cont>),                 //        sobel_0_debug.cont
		.sobel_0_debug_state                (<connected-to-sobel_0_debug_state>),                //                     .state
		.sobel_0_signals_done               (<connected-to-sobel_0_signals_done>),               //      sobel_0_signals.done
		.sobel_0_signals_ready              (<connected-to-sobel_0_signals_ready>),              //                     .ready
		.sw_export_export                   (<connected-to-sw_export_export>),                   //            sw_export.export
		.sdram_clk_clk                      (<connected-to-sdram_clk_clk>),                      //            sdram_clk.clk
		.system_ref_clk_clk                 (<connected-to-system_ref_clk_clk>),                 //       system_ref_clk.clk
		.system_ref_reset_reset             (<connected-to-system_ref_reset_reset>)              //     system_ref_reset.reset
	);

